/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App.frontend;

import App.dao.TurmaDAO;
import App.model.Aluno;
import App.model.Turma;
import App.service.AlunoService;
import java.awt.HeadlessException;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lexmibel Guidion
 */
public class AlunosFormEdit extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlunosFormEdit.class.getName());

    /**
     * Creates new form AlunosForm
     */
    public AlunosFormEdit() {
        initComponents();
        carregarTurmas();
        carregarAlunos();
    }
    
    // carregar turmas 
    public void carregarTurmas() {
        TurmaDAO turmaDAO = new TurmaDAO();
        List<Turma> turmasLista = turmaDAO.listarTodas();
        
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel();
        modelo.addElement("-- selecione turma");
        
        for(Turma t : turmasLista){
            modelo.addElement(t.getNome());
        }
        
        this.selectTurmas.setModel(modelo);
    }
    
    // carregar alunos 
    public void carregarAlunos() {
        AlunoService serviceAluno = new AlunoService();
        List<Aluno> alunosLista = serviceAluno.listarTodos();
        
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel();
        modelo.addElement("-- selecione o codigo do estudante");
        
        for(Aluno a : alunosLista){
            modelo.addElement(a.getNumeroEstudante());
        }
        
        this.selectAluno.setModel(modelo);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputNomeEncarregado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        selectTurmas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        inputContacto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputDataMatricula = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        selectAluno = new javax.swing.JComboBox<>();
        btnBuscarAluno = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabel6.setText("Contacto:");

        jTextField4.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar dados de estudante");

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabel2.setText("Selecione turma");

        inputNome.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabel3.setText("Nome do Encarregado:");

        inputNomeEncarregado.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabel4.setText("Nome:");

        selectTurmas.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        selectTurmas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabel5.setText("Contacto:");

        inputContacto.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabel7.setText("Data da matricula (AAAA-MM-DD)");

        inputDataMatricula.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N

        btnCancelar.setBackground(new java.awt.Color(255, 0, 51));
        btnCancelar.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");

        btnSalvar.setBackground(new java.awt.Color(0, 51, 51));
        btnSalvar.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Cadastrar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabel8.setText("Selecione o aluno");

        selectAluno.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        selectAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscarAluno.setBackground(new java.awt.Color(0, 51, 204));
        btnBuscarAluno.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        btnBuscarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarAluno.setText("Buscar");
        btnBuscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(inputNome)
                    .addComponent(inputNomeEncarregado)
                    .addComponent(jLabel5)
                    .addComponent(inputContacto)
                    .addComponent(selectTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDataMatricula)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(selectAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarAluno)))
                .addGap(399, 399, 399))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNomeEncarregado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        AlunoService serviceAluno = new AlunoService();
        Aluno aluno = serviceAluno.buscarPorNrEstudante(this.selectAluno.getSelectedItem().toString());

        // salvar alteracoes
        try {
            TurmaDAO turmaDAO = new TurmaDAO();
            Aluno alunoEdit = new Aluno(
                    this.inputNome.getText(), 
                    aluno.getNumeroEstudante(), 
                    this.inputNomeEncarregado.getText(), 
                    this.inputContacto.getText(), 
                    turmaDAO.buscarPorNome(this.selectTurmas.getSelectedItem().toString()),
                    LocalDate.of(Integer.parseInt(this.inputDataMatricula.getText().substring(0, 4)), Integer.parseInt(this.inputDataMatricula.getText().substring(5, 7)), Integer.parseInt(this.inputDataMatricula.getText().substring(8, 10)))
            );
            serviceAluno.atualizar(alunoEdit);
            JOptionPane.showMessageDialog(this, "Alteracao feita com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar novos dados: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnBuscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlunoActionPerformed
        // pegar dados do aluno
        AlunoService serviceAluno = new AlunoService();
        Aluno aluno = serviceAluno.buscarPorNrEstudante(this.selectAluno.getSelectedItem().toString());
        this.inputNome.setText(aluno.getNome());
        this.inputNomeEncarregado.setText(aluno.getEncarregado());
        this.inputContacto.setText(aluno.getContacto());
        this.inputDataMatricula.setText(aluno.getDataMatricula().toString());
        
        int indexTurma;
        switch (aluno.getTurma().getNome()) {
            case "INFORMATICA" -> indexTurma = 1;
            case "GESTAO" -> indexTurma = 2;
            case "DIREITO" -> indexTurma = 3;
            case "CONTABILIDADE" -> indexTurma = 4;
            default -> indexTurma = 0;
        }
        this.selectTurmas.setSelectedIndex(indexTurma);
    }//GEN-LAST:event_btnBuscarAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AlunosFormEdit().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAluno;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField inputContacto;
    private javax.swing.JTextField inputDataMatricula;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputNomeEncarregado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox<String> selectAluno;
    private javax.swing.JComboBox<String> selectTurmas;
    // End of variables declaration//GEN-END:variables
}
